file_name='Demon Slayer'
job_name='디어사이드'

info={
    'common':
    {
        'common_damage':'34184',
        'common_ele':'447'
        
        },
    'skill':
    [
        {'skillname':'분마검',
         'reqlvl':'30',
         'maxlvl':'38',
         'lvl_interval':'2',
         'damage':'504278',
         'talisman':False,
         'synergy':None
         },
        {'skillname':'혈화난무',
         'reqlvl':'35',
         'maxlvl':'36',
         'lvl_interval':'2',
         'damage':'559871',
         'talisman':False
         },
        {'skillname':'마인의 군대',
         'reqlvl':'40',
         'maxlvl':'23',
         'lvl_interval':'3',
         'damage':'1007033',
         'talisman':True
         },
        {'skillname':'콜 다이무스',
         'reqlvl':'45',
         'maxlvl':'31',
         'lvl_interval':'2',
         'damage':'1130972',
         'talisman':True
         },
        {'skillname':'혈마검',
         'reqlvl':'70',
         'maxlvl':'18',
         'lvl_interval':'2',
         'damage':'1002177',
         'talisman':False
         },
        {'skillname':'암연격-기가슬래쉬',
         'reqlvl':'75',
         'maxlvl':'16',
         'lvl_interval':'2',
         'damage':'983919',
         'talisman':False
         },
        {'skillname':'비인외도-극',
         'reqlvl':'80',
         'maxlvl':'13',
         'lvl_interval':'2',
         'damage':'957404',
         'talisman':False
         },
        {'skillname':'파계검-라그나로크',
         'reqlvl':'85',
         'maxlvl':'5',
         'lvl_interval':'5',
         'damage':'2206309',
         'talisman':False
         },
        {'skillname':'혈문지괴검',
         'reqlvl':'95',
         'maxlvl':'6',
         'lvl_interval':'2',
         'damage':'1351696',
         'talisman':False
         },
        {'skillname':'비인검-알카트라즈',
         'reqlvl':'100',
         'maxlvl':'2',
         'lvl_interval':'5',
         'damage':'3630067',
         'talisman':False
         }
        ]
    }
